config/routes.rb
Rails.application.routes.draw do
  devise_for :sellers
  devise_for :users
resources :homes do
  collection do
    get :contact_us
    get :about_us
    get :product_detail
    get :category
  end
end

namespace :seller do
  resources :homes do
  end
  resources :profiles do
  end 
end

authenticated :seller do
  root :to => 'seller/homes#index'
end
root 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ac.rb
class Ac < ApplicationRecord
  belongs_to :brands
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  
  has_many :mobile_details
  has_many :tv_details
  has_many :laptop_details
  has_many :acs
  has_many :fridges
  has_many :cameras
  has_many :microwaves
end

app/models/camera.rb
class Camera < ApplicationRecord
  belongs_to :brands

end

app/models/fridge.rb
class Fridge < ApplicationRecord
  belongs_to :brands
  
end

app/models/laptop_detail.rb
class LaptopDetail < ApplicationRecord
  belongs_to :brand
  
end

app/models/microwave.rb
class Microwave < ApplicationRecord
  belongs_to :brands
  
end

app/models/mobile_detail.rb
class MobileDetail < ApplicationRecord
  
  belongs_to :brand
end

app/models/seller.rb
class Seller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/tv_detail.rb
class TvDetail < ApplicationRecord
  belongs_to :brand

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :primary_cell, :secondary_cell, :residential_address,  :shop_address, :gender, :DOB, :approve])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end

  def category
  	  render 'category'
  end

  def product_detail
  	 render 'product_detail'
  end

  def about_us
     render 'about_us'
  end

  def contact_us
     render 'contact_us'
  end
end

app/controllers/seller/homes_controller.rb
class Seller::HomesController < ApplicationController
  def index
    if seller_signed_in?
      if current_seller.approve == false
        redirect_to edit_seller_registration_path
      else
      end
    end
  end
end

app/controllers/seller/profiles_controller.rb
class Seller::ProfilesController < ApplicationController

 def new
   @seller = Seller.new
 end

 def create
    #debugger
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/seller/homes_helper.rb
module Seller::HomesHelper
end

app/helpers/seller/profiles_helper.rb
module Seller::ProfilesHelper
end

app/views/homes/_footer.html.erb
<div class="gap"></div>
    </div>

    <footer class="main-footer">
            <div class="container">
                <div class="row row-col-gap" data-gutter="60">
                    <div class="col-md-3">
                        <h4 class="widget-title-sm">TheBox Shop</h4>
                        <p>Primis condimentum conubia iaculis tincidunt taciti tortor eget et venenatis augue curabitur</p>
                        <ul class="main-footer-social-list">
                            <li>
                                <a class="fa fa-facebook" href="#"></a>
                            </li>
                            <li>
                                <a class="fa fa-twitter" href="#"></a>
                            </li>
                            <li>
                                <a class="fa fa-pinterest" href="#"></a>
                            </li>
                            <li>
                                <a class="fa fa-instagram" href="#"></a>
                            </li>
                            <li>
                                <a class="fa fa-google-plus" href="#"></a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h4 class="widget-title-sm">Popular Tags</h4>
                        <ul class="main-footer-tag-list">
                            <li><a href="#">New Season</a>
                            </li>
                            <li><a href="#">Watches</a>
                            </li>
                            <li><a href="#">woman</a>
                            </li>
                            <li><a href="#">classic</a>
                            </li>
                            <li><a href="#">modern</a>
                            </li>
                            <li><a href="#">blue</a>
                            </li>
                            <li><a href="#">shoes</a>
                            </li>
                            <li><a href="#">running</a>
                            </li>
                            <li><a href="#">jeans</a>
                            </li>
                            <li><a href="#">sports</a>
                            </li>
                            <li><a href="#">laptops</a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h4 class="widget-title-sm">Newsletter</h4>
                        <form>
                            <div class="form-group">
                                <label>Sign up to the newsletter</label>
                                <input class="newsletter-input form-control" placeholder="Your e-mail address" type="text" />
                            </div>
                            <input class="btn btn-primary" type="submit" value="Sign up" />
                        </form>
                    </div>
                </div>
                <ul class="main-footer-links-list">
                    <li><a href="#">About Us</a>
                    </li>
                    <li><a href="#">Jobs</a>
                    </li>
                    <li><a href="#">Legal</a>
                    </li>
                    <li><a href="#">Support & Customer Service</a>
                    </li>
                    <li><a href="#">Blog</a>
                    </li>
                    <li><a href="#">Privacy</a>
                    </li>
                    <li><a href="#">Terms</a>
                    </li>
                    <li><a href="#">Press</a>
                    </li>
                    <li><a href="#">Shipping</a>
                    </li>
                    <li><a href="#">Payments & Refunds</a>
                    </li>
                </ul>
                <%= image_tag("test_footer2.png", :class => "main-footer-img", :alt => "Image Alternative text", :title => "Image Title") %>

            </div>
        </footer>
        <div class="copyright-area">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <p class="copyright-text">Copyright &copy; <a href="#">TheBox</a> 2014. Designed my remtsoy. All rights reseved</p>
                    </div>
                    <div class="col-md-6">
                        <ul class="payment-icons-list">
                            <li>
                                <%= image_tag("payment/visa-straight-32px.png", :alt => "Image Alternative text", :title => "Pay with Visa") %>
                            </li>
                            <li>
                                <%= image_tag("payment/mastercard-straight-32px.png", :alt => "Image Alternative text" , :title => "Pay with Mastercard") %>
                            </li>
                            <li>
                                <%= image_tag("payment/paypal-straight-32px.png", :alt => "Image Alternative text" , :title => "Pay with PayPal") %>
                            </li>
                            <li>
                                <%= image_tag("payment/visa-electron-straight-32px.png", :alt => "Image Alternative text" , :title => "Pay with Visa-electron") %>
                            </li>
                            <li>
                                <%= image_tag("payment/maestro-straight-32px.png", :alt => "Image Alternative text" , :title => "Pay with Meastro") %>
                            </li>
                            <li>
                                <%= image_tag("payment/discover-straight-32px.png", :alt => "Image Alternative text" , :title => "Pay with Discover") %>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
</div>

app/views/homes/about_us.html.erb
<div class="global-wrapper clearfix" id="global-wrapper">
        <div class="demo_changer" id="demo_changer">
            <div class="demo-icon fa fa-sliders"></div>
            <div class="form_holder">
                <div class="line"></div>
                <p>Color Scheme</p>
                <div class="predefined_styles" id="styleswitch_area">
                    <a class="styleswitch" href="about-usc392.html?default=true" style="background:#486D97;"></a>
                    <a class="styleswitch" href="#" data-src="bright-turquoise" style="background:#0EBCF2;"></a>
                    <a class="styleswitch" href="#" data-src="turkish-rose" style="background:#B66672;"></a>
                    <a class="styleswitch" href="#" data-src="salem" style="background:#12A641;"></a>
                    <a class="styleswitch" href="#" data-src="hippie-blue" style="background:#4F96B6;"></a>
                    <a class="styleswitch" href="#" data-src="mandy" style="background:#E45E66;"></a>
                    <a class="styleswitch" href="#" data-src="green-smoke" style="background:#96AA66;"></a>
                    <a class="styleswitch" href="#" data-src="horizon" style="background:#5B84AA;"></a>
                    <a class="styleswitch" href="#" data-src="cerise" style="background:#CA2AC6;"></a>
                    <a class="styleswitch" href="#" data-src="brick-red" style="background:#cf315a;"></a>
                    <a class="styleswitch" href="#" data-src="de-york" style="background:#74C683;"></a>
                    <a class="styleswitch" href="#" data-src="shamrock" style="background:#30BBB1;"></a>
                    <a class="styleswitch" href="#" data-src="studio" style="background:#7646B8;"></a>
                    <a class="styleswitch" href="#" data-src="leather" style="background:#966650;"></a>
                    <a class="styleswitch" href="#" data-src="denim" style="background:#1A5AE4;"></a>
                    <a class="styleswitch" href="#" data-src="scarlet" style="background:#FF1D13;"></a>
                </div>
                <div class="line"></div>
                <p>Layout</p>
                <div class="predefined_styles"><a class="btn btn-xs" href="#" id="btn-wide">Wide</a>&nbsp;&nbsp;<a class="btn btn-xs" href="#" id="btn-boxed">Boxed</a>
                </div>
                <div class="line"></div>
                <p>Background Patterns</p>
                <div class="predefined_styles" id="patternswitch_area">
                    <a class="patternswitch" href="#" style="background-image: url(img/patterns/binding_light.png);"></a>
                    <a class="patternswitch" href="#" style="background-image: url(img/patterns/binding_dark.png);"></a>
                    <a class="patternswitch" href="#" style="background-image: url(img/patterns/dark_fish_skin.png);"></a>
                    <a class="patternswitch" href="#" style="background-image: url(img/patterns/dimension.png);"></a>
                    <a class="patternswitch" href="#" style="background-image: url(img/patterns/escheresque_ste.png);"></a>
                    <a class="patternswitch" href="#" style="background-image: url(img/patterns/food.png);"></a>
                    <a class="patternswitch" href="#" style="background-image: url(img/patterns/giftly.png);"></a>
                    <a class="patternswitch" href="#" style="background-image: url(img/patterns/grey_wash_wall.png);"></a>
                    <a class="patternswitch" href="#" style="background-image: url(img/patterns/ps_neutral.png);"></a>
                    <a class="patternswitch" href="#" style="background-image: url(img/patterns/pw_maze_black.png);"></a>
                    <a class="patternswitch" href="#" style="background-image: url(img/patterns/pw_pattern.png);"></a>
                    <a class="patternswitch" href="#" style="background-image: url(img/patterns/simple_dashed.png);"></a>
                </div>
                <div class="line"></div>
                <p>Background Images</p>
                <div class="predefined_styles" id="bgimageswitch_area">
                    <a class="bgimageswitch" href="#" style="background-image: url(img/switcher/bike.jpg);" data-src="img/backgrounds/bike.jpg"></a>
                    <a class="bgimageswitch" href="#" style="background-image: url(img/switcher/flowers.jpg);" data-src="img/backgrounds/flowers.jpg"></a>
                    <a class="bgimageswitch" href="#" style="background-image: url(img/switcher/wood.jpg);" data-src="img/backgrounds/wood.jpg"></a>
                    <a class="bgimageswitch" href="#" style="background-image: url(img/switcher/taxi.jpg);" data-src="img/backgrounds/taxi.jpg"></a>
                    <a class="bgimageswitch" href="#" style="background-image: url(img/switcher/phone.jpg);" data-src="img/backgrounds/phone.jpg"></a>
                    <a class="bgimageswitch" href="#" style="background-image: url(img/switcher/road.jpg);" data-src="img/backgrounds/road.jpg"></a>
                    <a class="bgimageswitch" href="#" style="background-image: url(img/switcher/keyboard.jpg);" data-src="img/backgrounds/keyboard.jpg"></a>
                    <a class="bgimageswitch" href="#" style="background-image: url(img/switcher/beach.jpg);" data-src="img/backgrounds/beach.jpg"></a>
                    <a class="bgimageswitch" href="#" style="background-image: url(img/switcher/street.jpg);" data-src="img/backgrounds/street.jpg"></a>
                    <a class="bgimageswitch" href="#" style="background-image: url(img/switcher/nature.jpg);" data-src="img/backgrounds/nature.jpg"></a>
                    <a class="bgimageswitch" href="#" style="background-image: url(img/switcher/bridge.jpg);" data-src="img/backgrounds/bridge.jpg"></a>
                    <a class="bgimageswitch" href="#" style="background-image: url(img/switcher/cameras.jpg);" data-src="img/backgrounds/cameras.jpg"></a>
                </div>
                <div class="line"></div>
            </div>
        </div>
        <%= render 'header' %>


        <div class="container">
            <header class="page-header">
                <h1 class="page-title">About Us</h1>
            </header>
            <div class="row">
                <div class="col-md-9">
                    <p class="lead">Nostra mollis justo duis dolor fringilla accumsan erat ac non dictumst vel convallis neque rutrum est dapibus viverra curae pharetra dui ad cum cum suscipit ipsum class cubilia dignissim id</p>
                </div>
            </div>
            <div class="gap gap-small"></div>
            <div class="row row-col-gap">
                <div class="col-md-8">
                    <%= image_tag("street_960x480.jpg", :class => "full_width", :alt => "Image Alternative text", :title => "Image Title") %>

                </div>
                <div class="col-md-4">
                    <h3 class="widget-title">Our Story</h3>
                    <p>Sodales odio semper ornare proin condimentum senectus lacinia nullam malesuada scelerisque laoreet sodales fames sollicitudin tortor elementum luctus mus mi curae magnis adipiscing morbi leo fermentum sociosqu pharetra lectus lacus</p>
                    <p>Class convallis viverra sagittis imperdiet nunc lacinia suspendisse semper in non nostra vestibulum cras tempor mi ut bibendum auctor nam</p>
                    <p>Felis vehicula mollis dignissim dolor vel consequat iaculis dignissim semper curae nibh himenaeos quis malesuada sem fusce magna magnis magna</p>
                    <p>Dictumst eleifend vitae non massa potenti euismod nunc inceptos cubilia</p>
                </div>
            </div>
            <div class="gap gap-small"></div>
            <div class="row row-col-gap">
                <div class="col-md-6">
                    <h3 class="widget-title">The Community</h3>
                    <p>Etiam metus libero elit euismod quisque quisque eleifend dapibus fames ultrices sociis erat nunc adipiscing enim inceptos posuere pellentesque egestas</p>
                    <p>Ut vulputate urna vel posuere lorem lacinia cursus auctor nisl elementum bibendum suspendisse hac venenatis ipsum justo dolor platea imperdiet nibh congue adipiscing praesent primis montes ante nullam penatibus luctus</p>
                    <p>Hac sit quam id ante montes senectus dui praesent magnis</p>
                </div>
                <div class="col-md-6">

                  <%= image_tag("girls_party_smile_550x210.jpg", :class => "full_width", :alt => "Image Alternative text", :title => "Image Title") %>
                </div>
            </div>
            <div class="gap gap-small"></div>
            <div class="row row-col-gap">
                <div class="col-md-9">
                    <div class="row row-sm-gap" data-gutter="10">
                        <div class="col-md-2">
                          <%= image_tag("cup_on_red_300x300.jpg", :class => "full_width", :alt => "Image Alternative text", :title => "Image Title") %>

                        </div>
                        <div class="col-md-2">
                          <%= image_tag("rail_road_300x300.jpg", :class => "full_width", :alt => "Image Alternative text", :title => "Image Title") %>
                        </div>
                        <div class="col-md-2">
                            <%= image_tag("foots_and_grass_300x300.jpg", :class => "full_width", :alt => "Image Alternative text", :title => "Image Title") %>
                        </div>
                        <div class="col-md-2">
                          <%= image_tag("shoes-woman-girl-sport-jogging_300x300.jpg", :class => "full_width", :alt => "Image Alternative text", :title => "Image Title") %>

                        </div>
                        <div class="col-md-2">
                          <%= image_tag("the_violin_300x300.jpg", :class => "full_width", :alt => "Image Alternative text", :title => "Image Title") %>

                        </div>
                        <div class="col-md-2">
                          <%= image_tag("sorry_to_bust_your_bubble_300x300.jpg", :class => "full_width", :alt => "Image Alternative text", :title => "Image Title") %>

                        </div>
                        <div class="col-md-2">
                          <%= image_tag("my_ice_cream_and_your_ice_cream_spoons_300x300.jpg", :class => "full_width", :alt => "Image Alternative text", :title => "Image Title") %>

                        </div>
                        <div class="col-md-2">
                          <%= image_tag("a_dreamy_jump_300x300.jpg", :class => "full_width", :alt => "Image Alternative text", :title => "Image Title") %>

                        </div>
                        <div class="col-md-2">
                          <%= image_tag("lack_of_blue_depresses_me_300x300.jpg", :class => "full_width", :alt => "Image Alternative text", :title => "Image Title") %>
                        </div>
                        <div class="col-md-2">
                          <%= image_tag("ijump_300x300.jpg", :class => "full_width", :alt => "Image Alternative text", :title => "Image Title") %>

                        </div>
                        <div class="col-md-2">
                          <%= image_tag("dangle_300x300.jpg", :class => "full_width", :alt => "Image Alternative text", :title => "Image Title") %>

                        </div>
                        <div class="col-md-2">
                          <%= image_tag("step_up_300x300.jpg", :class => "full_width", :alt => "Image Alternative text", :title => "Image Title") %>

                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <h3 class="widget-title">Behind The Scenes</h3>
                    <p>Eget ligula libero torquent semper at sollicitudin litora ultricies metus a justo in sagittis malesuada maecenas nec fringilla leo tempor</p>
                    <p>Faucibus conubia lacus faucibus varius odio montes accumsan faucibus sociis</p>
                    <p>Id porta quisque dictum aliquet nec cum parturient congue id</p>
                </div>
            </div>
            <div class="gap gap-small"></div>
        </div>

        <%= render 'footer' %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElectroCart</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/seller/profiles/new.html.erb
<% content_for :title, "Create Profile | Electro Cart" %>
<div class="container" style="padding-top: 20px;">
  <div class="row">
    <div class="col-md-12 no-pad-xs">
      <div class="row login_signup_heading" style="padding:0px;margin:0px;">
        <div class="col-md-12">
          <center><h3 class="heading_text">Create Profile</h3></center>
        </div>
      </div>
        <div class="jumbotron" style="padding-top:1em;padding-bottom:1em; background-color: rgba(48,110,255,0.7); border-radius:0 0 1em 1em;">
        <div class="row">
          <div class="col-md-12 login_signup_panel">
          <%= form_for :@seller, url: seller_profiles_path do |form| %>
            <% if @seller.errors.any? %>
              <div class="form-group alert alert-error alert-block" id="error_explanation">
                <button type="button" class="close" data-dismiss="alert">x</button>
                <h4 class="heading_error"><%= pluralize(@seller.errors.count, "error") %> prohibited this Profile from being saved:</h4>
                <% @seller.errors.full_messages.each do |msg| %>
                    <h5 class="heading_error"><%= msg%></h5>
                <% end %>
              </div>
            <%end%>

            <div class="row">
              <div class="col-xs-12 col-md-4">
                <div class="form-group" style="margin-top:0.5em;">
                  <div class="row">
                    <center>
                      <%= image_tag('user.png', {id: "residential_image", style: "width:12em;height:12em;",class: "my_img img-responsive img-thumbnail img-circle",alt: "User Profile Image"}) %>
                      <input data-toggle="modal" data-target="#addPhoto" class="btn btn-block btn-info" type="button" value="Add Avatar" style="width: 50%;margin-top:0.5em;">
                    </center>
                  </div>
                </div>
              </div>
              <div class="col-xs-12 col-md-8">
                <div class="row">
                  <div class="col-md-12"><center><h3 class="heading_text" style="font-size:1.1em;">Personal Detail</h3></center></div>
                  <div class="col-xs-12 col-md-6" style="margin-top:-1em;">
                    <%= form.label :first_name, class: "login_signup_label" %>
                    <%= form.text_field :first_name ,class: 'form-control my_text_field', required: true%>
                    <%= form.label :last_name, class: "login_signup_label"%>
                    <%= form.text_field :last_name, class: 'my_text_field form-control', required: true%>
                    <%= form.label :gender, "Gender", class:"label" %><br />
                    <%= form.select :gender, options_for_select([ "Male", "Female" ]),{prompt: "Select Gender"}, {class: 'form-control', style:"font-size: 1em;"}%>
                    <%= form.label :dob, "Date of Birth", class:"label" %><br />
                    <%= form.date_select :dob, {start_year:1950, prompt: true}, {class: 'form-control', style:"font-size: 0.8em;display:inline-block;width:33%;"}%>
                  </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-12"><center><h3 class="heading_text" style="font-size:1.1em;">Contact Detail</h3></center></div>
                  <div class="col-xs-12 col-md-6" style="margin-top:-1em;">
                    <%= form.label :primary_cell, "Primary Mobile Number", class: "login_signup_label" %>
                    <%= form.number_field :primary_cell, class: 'form-control my_text_field', required: true%>
                    <%= form.label :secondary_cell, "Landline Number", class: "login_signup_label"%>
                    <%= form.number_field :secondary_cell, class: 'my_text_field form-control'%>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-12"><center><h3 class="heading_text" style="font-size:1.1em;">Address Detail</h3></center></div>

                    <div class="col-xs-12 col-md-6" style="margin-top:-1em;">
                      <%= form.label :residential_address, "Residential Address", class: "login_signup_label"%>
                      <%= form.text_area :residential_address, class: 'my_text_field form-control', required: true%>
                      <%= form.label :shop_address, "Shop Address", class: "login_signup_label"%>
                      <%= form.text_area :shop_address, class: 'my_text_field form-control', required: true%>
                    </div>
                </div>
              </div>
            </div>
            <br>
            <div class="col-md-5"></div>
            <div class="col-md-2">
              <div class="row">
                <div class="actions">
                  <%= form.submit  "Save" ,class: 'btn btn-block btn-outline btn-primary active_button', style: "font-weight:bold;font-family: 'Merriweather', serif; color:#FFFFFF" %>
                </div>
              </div>
            </div>
            <div class="col-md-5"></div>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sellers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>